project:
  type: website

website:
  title: "Bryan West"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
