project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - teaching.qmd
    - publications.qmd
    - talks.qmd
    - posts.qmd
    - contact.qmd

website:
  title: "Bryan West"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: teaching.qmd
        text: Teaching
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: posts.qmd
        text: Posts
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
